### ISSUE TITLE
ResolvePackageNotFound: python=3.1 when installing

### ISSUE THREAD

**Issue by thjimmylee** [netbiolab/scHumanNet#2]
Hi, I've got the problem below when installing. 
I did `conda search python` and it happen that there was no python version 3.1 on the list too

```$  conda install --file ./scHumanNet/packages/requirements_scHumanNet.txt
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.

ResolvePackageNotFound: 
  - python=3.1

**Comment by JunhaCha** [comment]
Hi Jimmy,

I've uploaded a yml file in the packages folder, and modified the installation direction so that you could directly configure the necessary conda envrionment. Could you check if the new direction works for you and let me know?

**Comment by thjimmylee** [comment]
Thanks Junha for the quick response!! 

I think the installation works!! Just to note that in the instruction, you missed to comment out `and check whether appropriate files have been installed`

```$ conda activate scHumanNet and check whether appropriate files have been installed```
