### ISSUE TITLE
question about SCINET

### ISSUE THREAD

**Issue by wangj26** [netbiolab/scHumanNet#3]
Hi,

When running the examples, I found the functions from SCINET can not be found in the system. When I checked these functions in the SCINET github, I can also not find these functions. Could you please give me some suggestions how to run these functions.

Thanks,

**Comment by JunhaCha** [comment]
Hello,

Could you tell me the names of the functions you could not load? Also, did you check if you have properly loaded the SCINET library? Check also, if you have loaded the modified ACTIONet package containing the reference HumanNet provided in the package folder, as written in the readme section.
