### ISSUE TITLE
Is scHumanNet applicable to other species？

### ISSUE THREAD

**Issue by schnappi-wkl** [netbiolab/scHumanNet#4]
Is scHumanNet applicable to other species？ such as mouse, monkey,pig etc 
thanks

**Comment by JunhaCha** [comment]
Hi, thank you for the question.

**Comment by JunhaCha** [comment]
Hi,

thank you for your question. the HumanNet that is used as reference was modeled based on various data from human samples, therefore there may be differences according to organisms. If you are willing to assume that the functions of the particular cell / gene you are studying should not differ at the systemic level you could just map the the output of scHumanNet human genes to your organism of interest (for example mouse models). If not, I recommend modifying the package manually to insert your own reference network, as the current package only supports the human gene-gene association network.
